[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.ffi]
enabled = true

[rpc_endpoints]
sepolia = "https://sepolia-01.astar.network/"
osaki = "http://rpc.stg.hypersonicl2.com/"
shibuya = "https://evm.shibuya.astar.network"
local = "http://localhost:8545"
